# Pre-commit hooks configuration for CueLABS™ Platform
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: check-yaml
        name: Check YAML
      - id: check-json
        name: Check JSON
      - id: check-toml
        name: Check TOML
      - id: check-xml
        name: Check XML
      - id: check-added-large-files
        name: Check for Added Large Files
        args: ['--maxkb=1000']
      - id: check-case-conflict
        name: Check for Case Conflicts
      - id: check-merge-conflict
        name: Check for Merge Conflicts
      - id: debug-statements
        name: Debug Statements (Python)
      - id: detect-private-key
        name: Detect Private Key

  # JavaScript/TypeScript specific hooks (using local system)
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npx eslint --fix
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: true

      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        pass_filenames: true

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: npx tsc --noEmit
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

  # Commit message validation (disabled - incompatible with IDE workflow)
  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v4.2.0
  #   hooks:
  #     - id: conventional-pre-commit
  #       name: Conventional Commit
  #       stages: [commit-msg]

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

# Configuration for specific hooks
default_language_version:
  node: system

# Exclude certain files/directories
exclude: |
  (?x)^(
    \.next/.*|
    node_modules/.*|
    \.git/.*|
    \.env.*|
    package-lock\.json|
    \.DS_Store|
    scripts/.*|
    public/.*\.js
  )$
