blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/cuesoftinc/cuelabs-platform/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/cuesoftinc/cuelabs-platform/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📖 Documentation
    url: https://github.com/cuesoftinc/cuelabs-platform#readme
    about: Check our documentation for setup and usage guides
