name: Feature Request
description: Suggest an idea for CueLABS™
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem-statement
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the specific use case or scenario where this feature would be helpful.
      placeholder: |
        As a [type of user], I want [feature] so that [benefit].

        Example scenario:
        1. User does X
        2. Feature helps with Y
        3. User achieves Z
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have also considered...

  - type: dropdown
    id: feature-area
    attributes:
      label: Which area of the platform does this feature relate to?
      multiple: true
      options:
        - Authentication
        - Dashboard
        - Bounty System
        - Marketplace
        - Leaderboards
        - Admin Panel
        - API
        - Documentation
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
        - Blocking my usage

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
